# Generated by Django 5.2.12 on 2026-04-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, help_text='Student photo', null=True, upload_to='student_images/'),
        ),
    ]
