# Generated by Django 5.2.4 on 2026-03-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_result_terminal_alter_attendance_id'),
        ('core', '0010_alter_result_unique_together'),
    ]

    operations = [
    ]
