# Generated by Django 4.1.13 on 2026-06-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_achievement_branch_busroute_certificatetemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='value',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
