# Generated by Django 5.2.15 on 2026-06-15 17:35

import django.db.models.deletion
from django.db import migrations, models


def populate_class_sections(apps, schema_editor):
    """Create Class entries from existing student_class/section/level combinations."""
    Student = apps.get_model('core', 'Student')
    Class = apps.get_model('core', 'Class')

    # Get unique combinations of (student_class, section, level)
    unique_combos = Student.objects.values('student_class', 'section', 'level').distinct()

    # Track created Class objects
    class_map = {}
    for combo in unique_combos:
        class_name = combo['student_class'] or 'Unknown'
        section = combo['section']
        level = combo['level']

        class_obj, created = Class.objects.get_or_create(
            name=class_name,
            section=section,
            level=level,
        )
        class_map[(class_name, section, level)] = class_obj

    # Update Student records with class_section FK
    for student in Student.objects.all():
        class_name = student.student_class or 'Unknown'
        section = student.section
        level = student.level

        key = (class_name, section, level)
        if key in class_map:
            student.class_section = class_map[key]
            student.save(update_fields=['class_section'])


def reverse_populate_class_sections(apps, schema_editor):
    """Reverse: clear class_section references but keep Class records for rollback."""
    Student = apps.get_model('core', 'Student')
    Student.objects.all().update(class_section=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_systemconfig_description_alter_systemconfig_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Class/Grade designation (e.g., 1, 5, 10, XI, XII, Semester 1)', max_length=20)),
                ('section', models.CharField(help_text='Section/Division (e.g., A, B, C)', max_length=5)),
                ('level', models.CharField(choices=[('school', 'School Level (1-10)'), ('college', 'College Level (XI-XII)'), ('bachelor', 'Bachelor Level')], help_text='Education level for this class', max_length=20)),
                ('capacity', models.PositiveIntegerField(blank=True, default=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Class/Section',
                'verbose_name_plural': 'Classes/Sections',
                'ordering': ['level', 'name', 'section'],
                'unique_together': {('name', 'section', 'level')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='class_section',
            field=models.ForeignKey(blank=True, help_text='Normalized class/section reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.class'),
        ),
        migrations.AddField(
            model_name='subject',
            name='classes',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to assign to all classes', related_name='subjects', to='core.class'),
        ),
        migrations.RunPython(populate_class_sections, reverse_populate_class_sections),
    ]
